# Generated by Django 2.1.1 on 2018-09-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180920_2221'),
        ('catalog', '0002_auto_20180920_2201'),
    ]

    operations = [
    ]
