# Generated by Django 2.1.1 on 2018-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_20180920_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='catalogimages'),
        ),
    ]
