# Generated by Django 2.1.1 on 2018-09-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180921_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='catalog.ProductGroup'),
        ),
    ]
